module.exports = {
  AE: ['g', 'i'],
  AF: ['p', 'g', 'i'],
  BH: ['g', 'i'],
  CN: ['g'],
  CX: ['g'],
  DJ: ['g', 'i'],
  DZ: ['g', 'i'],
  EG: ['g', 'i'],
  EH: ['g', 'i'],
  ER: ['g', 'i'],
  ET: ['g'],
  HK: ['g'],
  IL: ['g', 'i'],
  IN: ['g'],
  IQ: ['g', 'i'],
  IR: ['p', 'g', 'i'],
  JO: ['g', 'i'],
  JP: ['g'],
  KM: ['g', 'i'],
  KR: ['g'],
  KW: ['g', 'i'],
  LB: ['g', 'i'],
  LY: ['g', 'i'],
  MA: ['g', 'i'],
  MO: ['g'],
  MR: ['g', 'i'],
  OM: ['g', 'i'],
  PS: ['g', 'i'],
  QA: ['g', 'i'],
  SA: ['i', 'g'],
  SD: ['g', 'i'],
  SG: ['g'],
  SY: ['g', 'i'],
  TD: ['g', 'i'],
  TH: ['g'],
  TN: ['g', 'i'],
  TW: ['g'],
  YE: ['g', 'i'],
};
