module.exports = {
  week: [
    'domingo',
    'lunes',
    'martes',
    'miércoles',
    'jueves',
    'viernes',
    'sábado',
  ],
  weekNarrow: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
  g: {
    name: 'después de Cristo',
    nameAbbr: 'd. C.',
    month: [
      'enero',
      'febrero',
      'marzo',
      'abril',
      'mayo',
      'junio',
      'julio',
      'agosto',
      'septiembre',
      'octubre',
      'noviembre',
      'diciembre',
    ],
  },
  i: {
    name: 'AH',
    nameAbbr: 'AH',
    month: [
      'muharram',
      'safar',
      'rabiʻ I',
      'rabiʻ II',
      'jumada I',
      'jumada II',
      'rajab',
      'shaʻban',
      'ramadán',
      'shawwal',
      'dhuʻl-qiʻdah',
      'dhuʻl-hijjah',
    ],
  },
  p: {
    name: 'AP',
    nameAbbr: 'AP',
    month: [
      'farvardin',
      'ordibehesht',
      'khordad',
      'tir',
      'mordad',
      'shahrivar',
      'mehr',
      'aban',
      'azar',
      'dey',
      'bahman',
      'esfand',
    ],
  },
};
