module.exports = {
  week: [
    'dimanche',
    'lundi',
    'mardi',
    'mercredi',
    'jeudi',
    'vendredi',
    'samedi',
  ],
  weekNarrow: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
  g: {
    name: 'après Jésus-Christ',
    nameAbbr: 'ap. J.-C.',
    month: [
      'janvier',
      'février',
      'mars',
      'avril',
      'mai',
      'juin',
      'juillet',
      'août',
      'septembre',
      'octobre',
      'novembre',
      'décembre',
    ],
  },
  p: {
    name: 'Anno Persico',
    nameAbbr: 'A. P.',
    month: [
      'farvardin',
      'ordibehešt',
      'khordâd',
      'tir',
      'mordâd',
      'šahrivar',
      'mehr',
      'âbân',
      'âzar',
      'dey',
      'bahman',
      'esfand',
    ],
  },
};
