module.exports = {
  week: [
    'domenica',
    'lunedì',
    'martedì',
    'mercoledì',
    'giovedì',
    'venerdì',
    'sabato',
  ],
  weekNarrow: ['D', 'L', 'M', 'M', 'G', 'V', 'S'],
  g: {
    name: 'dopo Cristo',
    nameAbbr: 'd.C.',
    month: [
      'gennaio',
      'febbraio',
      'marzo',
      'aprile',
      'maggio',
      'giugno',
      'luglio',
      'agosto',
      'settembre',
      'ottobre',
      'novembre',
      'dicembre',
    ],
  },
  p: {
    name: 'AP',
    nameAbbr: 'AP',
    month: [
      'Farvardin',
      'Ordibehesht',
      'Khordad',
      'Tir',
      'Mordad',
      'Shahrivar',
      'Mehr',
      'Aban',
      'Azar',
      'Dey',
      'Bahman',
      'Esfand',
    ],
  },
};
