module.exports = {
  week: ['yekşem', 'duşem', 'sêşem', 'çarşem', 'pêncşem', 'în', 'şemî'],
  weekNarrow: ['Y', 'D', 'S', 'Ç', 'P', 'Î', 'Ş'],
  g: {
    name: 'piştî zayînê',
    nameAbbr: 'PZ',
    month: [
      'rêbendanê',
      'reşemiyê',
      'adarê',
      'avrêlê',
      'gulanê',
      'pûşperê',
      'tîrmehê',
      'gelawêjê',
      'rezberê',
      'kewçêrê',
      'sermawezê',
      'berfanbarê',
    ],
  },
  p: {
    name: 'AP',
    nameAbbr: 'AP',
    month: [
      'Farvardin',
      'Ordibehesht',
      'Khordad',
      'Tir',
      'Mordad',
      'Shahrivar',
      'Mehr',
      'Aban',
      'Azar',
      'Dey',
      'Bahman',
      'Esfand',
    ],
  },
};
