module.exports = {
  week: [
    'zondag',
    'maandag',
    'dinsdag',
    'woensdag',
    'donderdag',
    'vrijdag',
    'zaterdag',
  ],
  weekNarrow: ['Z', 'M', 'D', 'W', 'D', 'V', 'Z'],
  g: {
    name: 'na Christus',
    nameAbbr: 'n.Chr.',
    month: [
      'januari',
      'februari',
      'maart',
      'april',
      'mei',
      'juni',
      'juli',
      'augustus',
      'september',
      'oktober',
      'november',
      'december',
    ],
  },
  p: {
    name: 'AP',
    nameAbbr: 'AP',
    month: [
      'Farvardin',
      'Ordibehesht',
      'Khordad',
      'Tir',
      'Mordad',
      'Shahrivar',
      'Mehr',
      'Aban',
      'Azar',
      'Dey',
      'Bahman',
      'Esfand',
    ],
  },
};
