module.exports = {
  week: [
    'niedziela',
    'poniedziałek',
    'wtorek',
    'środa',
    'czwartek',
    'piątek',
    'sobota',
  ],
  weekNarrow: ['n', 'p', 'w', 'ś', 'c', 'p', 's'],
  g: {
    name: 'naszej ery',
    nameAbbr: 'n.e.',
    month: [
      'stycznia',
      'lutego',
      'marca',
      'kwietnia',
      'maja',
      'czerwca',
      'lipca',
      'sierpnia',
      'września',
      'października',
      'listopada',
      'grudnia',
    ],
  },
  p: {
    name: 'AP',
    nameAbbr: 'AP',
    month: [
      'Farwardin',
      'Ordibeheszt',
      'Chordād',
      'Tir',
      'Mordād',
      'Szahriwar',
      'Mehr',
      'Ābān',
      'Āsar',
      'Déi',
      'Bahman',
      'Esfand',
    ],
  },
};
