module.exports = {
  week: [
    'niedziela',
    'poniedziałek',
    'wtorek',
    'środa',
    'czwartek',
    'piątek',
    'sobota',
  ],
  weekNarrow: ['n', 'p', 'w', 'ś', 'c', 'p', 's'],
  g: {
    name: 'naszej ery',
    nameAbbr: 'n.e.',
    month: [
      'stycznia',
      'lutego',
      'marca',
      'kwietnia',
      'maja',
      'czerwca',
      'lipca',
      'sierpnia',
      'września',
      'października',
      'listopada',
      'grudnia',
    ],
  },
  i: {
    name: 'AH',
    nameAbbr: 'AH',
    month: [
      'Muharram',
      'Safar',
      'Rabiʻ I',
      'Rabiʻ II',
      'Dżumada I',
      'Dżumada II',
      'Radżab',
      'Szaban',
      'Ramadan',
      'Szawwal',
      'Zu al-kada',
      'Zu al-hidżdża',
    ],
  },
  p: {
    name: 'AP',
    nameAbbr: 'AP',
    month: [
      'Farwardin',
      'Ordibeheszt',
      'Chordād',
      'Tir',
      'Mordād',
      'Szahriwar',
      'Mehr',
      'Ābān',
      'Āsar',
      'Déi',
      'Bahman',
      'Esfand',
    ],
  },
};
