module.exports = {
  week: [
    'domingo',
    'segunda-feira',
    'terça-feira',
    'quarta-feira',
    'quinta-feira',
    'sexta-feira',
    'sábado',
  ],
  weekNarrow: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
  g: {
    name: 'depois de Cristo',
    nameAbbr: 'd.C.',
    month: [
      'janeiro',
      'fevereiro',
      'março',
      'abril',
      'maio',
      'junho',
      'julho',
      'agosto',
      'setembro',
      'outubro',
      'novembro',
      'dezembro',
    ],
  },
  i: {
    name: 'AH',
    nameAbbr: 'AH',
    month: [
      'Muharram',
      'Safar',
      'Rabiʻ I',
      'Rabiʻ II',
      'Jumada I',
      'Jumada II',
      'Rajab',
      'Shaʻban',
      'Ramadan',
      'Shawwal',
      'Dhuʻl-Qiʻdah',
      'Dhuʻl-Hijjah',
    ],
  },
  p: {
    name: 'AP',
    nameAbbr: 'AP',
    month: [
      'Farvardin',
      'Ordibehesht',
      'Khordad',
      'Tir',
      'Mordad',
      'Shahrivar',
      'Mehr',
      'Aban',
      'Azar',
      'Dey',
      'Bahman',
      'Esfand',
    ],
  },
};
