module.exports = {
  week: [
    'Jumapili',
    'Jumatatu',
    'Jumanne',
    'Jumatano',
    'Alhamisi',
    'Ijumaa',
    'Jumamosi',
  ],
  weekNarrow: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
  g: {
    name: 'Baada ya Kristo',
    nameAbbr: 'BK',
    month: [
      'Januari',
      'Februari',
      'Machi',
      'Aprili',
      'Mei',
      'Juni',
      'Julai',
      'Agosti',
      'Septemba',
      'Oktoba',
      'Novemba',
      'Desemba',
    ],
  },
  i: {
    name: 'AH',
    nameAbbr: 'AH',
    month: [
      'Muharram',
      'Safar',
      'Rabiʻ I',
      'Rabiʻ II',
      'Jumada I',
      'Jumada II',
      'Rajab',
      'Shaʻban',
      'Ramadan',
      'Shawwal',
      'Dhuʻl-Qiʻdah',
      'Dhuʻl-Hijjah',
    ],
  },
  p: {
    name: 'AP',
    nameAbbr: 'AP',
    month: [
      'Farvardin',
      'Ordibehesht',
      'Khordad',
      'Tir',
      'Mordad',
      'Shahrivar',
      'Mehr',
      'Aban',
      'Azar',
      'Dey',
      'Bahman',
      'Esfand',
    ],
  },
};
