module.exports = {
  week: [
    'Pazar',
    'Pazartesi',
    'Salı',
    'Çarşamba',
    'Perşembe',
    'Cuma',
    'Cumartesi',
  ],
  weekNarrow: ['P', 'P', 'S', 'Ç', 'P', 'C', 'C'],
  g: {
    name: 'Milattan Sonra',
    nameAbbr: 'MS',
    month: [
      'Ocak',
      'Şubat',
      'Mart',
      'Nisan',
      'Mayıs',
      'Haziran',
      'Temmuz',
      'Ağustos',
      'Eylül',
      'Ekim',
      'Kasım',
      'Aralık',
    ],
  },
  p: {
    name: 'AP',
    nameAbbr: 'AP',
    month: [
      'Ferverdin',
      'Ordibeheşt',
      'Hordad',
      'Tir',
      'Mordad',
      'Şehriver',
      'Mehr',
      'Aban',
      'Azer',
      'Dey',
      'Behmen',
      'Esfend',
    ],
  },
};
